---
- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - instance

- hosts: ec2_instances
  gather_facts: true
  become: yes
  remote_user: ubuntu
  pre_tasks:
    - name: Install Python 2
      raw: sudo apt-get update; sudo apt-get -y install python
  roles:
    - docker